version: 1.0.{build}
image: Ubuntu2004
install:
  - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - node --version
  - npm --version
  - cd 1.health-indicator
  - npm install
build: off
test_script:
  - cd 1.health-indicator
  - npm run lint
  - npm test